spring:
  application:
    name: lifelab-be

  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3307/lifelab?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:apppass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # Flyway가 스키마 관리하므로 validate 권장 (개발 중엔 update도 가능)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true   # 기존 DB/볼륨이 있을 때 시작 편하게 해줌(개발용)

server:
  port: 8080